name: recette_magique
description: "Transformez vos livres de cuisine en un trésor numérique ! Cette application Flutter scanne, organise et catégorise vos recettes préférées grâce à l'OCR et à l'IA, les rendant accessibles et modifiables en un clin d"
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.6.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  google_fonts: ^7.0.0
  provider: ^6.1.2
  go_router: ^16.2.0

  firebase_core: ^4.3.0
  firebase_auth: ">=5.3.3"
  cloud_firestore: ">=5.5.0"
  firebase_storage: ^13.0.0
  firebase_analytics: ^12.1.0

  google_mlkit_text_recognition: 0.15.0
  image_picker: ">=1.1.2"
  cached_network_image: ^3.0.0
  http: ^1.0.0
  image: ^4.7.2
  shared_preferences: ^2.5.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true
  assets:
    - assets/icons/


flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/app_icon.png"
  remove_alpha_ios: true
